width = 0
height = 640

[[color_attachment]]
format = "rgba8"
clear = [0, 0, 0, 0]
start = "dont_care" # "dont_care", "clear", "load"
finish = "save" # "discard", "save"
sampler = "bg_masked"
sampler_type = "2D"

[[pipeline]]
material="TriBok"
vs = "bg_mask.vert"
fs = "bg_mask.frag"
blend = "off"
backfaces = true
colorwrite = true
zwrite = false
ztest = false