width = 0
height = 640

[[color_attachment]]
format = "rgba8"
clear = [0, 0, 0, 0]
start = "dont_care" # "dont_care", "clear", "load"
finish = "save" # "discard", "save"
sampler = "bokeh_hR"
sampler_type = "2D"

[[color_attachment]]
format = "rgba8"
clear = [0, 0, 0, 0]
start = "dont_care" # "dont_care", "clear", "load"
finish = "save" # "discard", "save"
sampler = "bokeh_hG"
sampler_type = "2D"

[[color_attachment]]
format = "rgba8"
clear = [0, 0, 0, 0]
start = "dont_care" # "dont_care", "clear", "load"
finish = "save" # "discard", "save"
sampler = "bokeh_hB"
sampler_type = "2D"

[[pipeline]]
material="TriBok"
vs = "bokeh_h.vert"
fs = "bokeh_h.frag"
blend = "off"
backfaces = true
colorwrite = true
zwrite = false
ztest = false