size_factor=1.0

[[color_attachment]]
format = "rgb8"
clear = [0, 0, 0, 0]
start = "clear" # "dont_care", "clear", "load"
finish = "save" # "discard", "save"
sampler = "colored_hair_strand"
sampler_type = "2D"

[[pipeline]]
material="TriMHS"
vs = "colored_hair_strand.vert"
fs = "colored_hair_strand.frag"
blend = "off"
backfaces = false
colorwrite = true
zwrite = false
ztest = false