size_factor = 0.5

[[color_attachment]]
format = "rgba8"
clear = [0, 0, 0, 0]
start = "dont_care" # "dont_care", "clear", "load"
finish = "save" # "discard", "save"
sampler = "tex_df_blur_u1"
sampler_type = "2D"

[[pipeline]]
material="TriBlr"
vs = "df_blur_up2.vert"
fs = "df_blur_up2.frag"
blend = "off"
backfaces = true
colorwrite = true
zwrite = false
ztest = false