width = 1024
height = 1024

[[color_attachment]]
format = "rgba8"
clear = [0, 0, 0, 0]
start = "clear" # "dont_care", "clear", "load"
finish = "save" # "discard", "save"
sampler = "tex_composite_makeup"
sampler_type = "2D"

[[pipeline]]
material="make01"
vs = "tex_makeup.vert"
fs = "tex_makeup.frag"
blend = "premul_alpha"
backfaces = true
colorwrite = true
zwrite = false
ztest = false
[pipeline.samplers]
tex0 = 0
tex1 = 1
tex2 = 2
tex3 = 3
tex4 = 4
tex5 = 5
tex6 = 6
tex7 = 7
